# Generated by Django 5.2.7 on 2025-10-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select type..."),
                            ("tshirt", "T-Shirt"),
                            ("trousers", "Trousers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select size..."),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                        ],
                        help_text="For T-Shirts only",
                        max_length=1,
                    ),
                ),
                (
                    "waist_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select waist size..."),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                            ("31", "31"),
                            ("32", "32"),
                            ("33", "33"),
                            ("34", "34"),
                            ("35", "35"),
                            ("36", "36"),
                            ("37", "37"),
                            ("38", "38"),
                            ("39", "39"),
                            ("40", "40"),
                            ("41", "41"),
                            ("42", "42"),
                        ],
                        help_text="For Trousers only",
                        max_length=2,
                    ),
                ),
                ("colour", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
