# Generated by Django 6.0 on 2026-01-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select type..."),
                            ("tshirt", "T-Shirt"),
                            ("trousers", "Trousers"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select size..."),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                        ],
                        help_text="For T-Shirts only",
                        max_length=1,
                    ),
                ),
                (
                    "waist_size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Select waist size..."),
                            ("28", "28"),
                            ("29", "29"),
                            ("30", "30"),
                            ("31", "31"),
                            ("32", "32"),
                        ],
                        help_text="For Trousers only",
                        max_length=2,
                    ),
                ),
                ("colour", models.CharField(max_length=20)),
            ],
        ),
    ]
